version: "3.7"

services: 
    web:
        build: ./project
        command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
        volumes: 
            - ./project:/app
        ports: 
            - 8002:8000
        environment: 
            - ENVIRONMENT=dev
            - TESTING=0

    redis:
        image: redis:6.0.9-alpine
        expose: 
            - 6379
        ports: 
            - 6379:6379
        restart: always